<?php

return [
    'daily' => [
        'enabled' => env('AI_ARTICLE_DAILY_ENABLED', true),
        'time' => env('AI_ARTICLE_DAILY_TIME', '08:00'),
        'timezone' => env('AI_ARTICLE_DAILY_TIMEZONE', 'Asia/Jakarta'),
        'max_company_reference_characters' => env('AI_ARTICLE_COMPANY_REFERENCE_LIMIT', 3400),
        'max_product_reference_characters' => env('AI_ARTICLE_PRODUCT_REFERENCE_LIMIT', 5600),
        'reference_files' => [
            'company' => env('AI_ARTICLE_COMPANY_PROFILE_PATH', base_path('../beacon_engineering_profile.md')),
            'products' => env('AI_ARTICLE_PRODUCT_REFERENCE_PATH', base_path('../dokumentasi_produk_dan_spesifikasi_be_profile.md')),
        ],
        'topics' => [
            [
                'topic' => 'sumur pantau dan pemantauan muka air tanah berkelanjutan',
                'angle' => 'jelaskan kenapa data muka air tanah yang konsisten lebih berguna daripada pengukuran sesekali',
                'audience' => 'pengelola sumber daya air, konsultan hidrologi, dan tim operasi lapangan',
                'product' => 'AWLR dan STESY',
                'product_headings' => ['Automatic Water Level Recorder', 'Smart Telemetry System'],
                'profile_keywords' => ['AWLR', 'STESY', 'Water Management'],
            ],
            [
                'topic' => 'membaca tren muka air untuk operasi bendungan dan irigasi',
                'angle' => 'bahas hubungan data level air, tren historis, dan keputusan teknis harian',
                'audience' => 'BBWS/BWS, pengelola bendungan, dan operator irigasi',
                'product' => 'AWLR',
                'product_headings' => ['Automatic Water Level Recorder'],
                'profile_keywords' => ['AWLR', 'Water Security', 'Dam Management'],
            ],
            [
                'topic' => 'curah hujan otomatis sebagai dasar kesiapsiagaan hidrologi',
                'angle' => 'buat artikel edukatif tentang pentingnya data hujan resolusi baik untuk membaca respons DAS',
                'audience' => 'pengelola pos hidrologi, dinas SDA, dan konsultan perencana',
                'product' => 'ARR',
                'product_headings' => ['Automatic Rain Recorder'],
                'profile_keywords' => ['ARR', 'Weather Forecast', 'Early Warning'],
            ],
            [
                'topic' => 'stasiun cuaca otomatis untuk memahami kondisi mikro di area infrastruktur air',
                'angle' => 'jelaskan kenapa parameter cuaca lokal membantu analisis operasional bendungan, irigasi, dan pertanian',
                'audience' => 'pengelola bendungan, irigasi, dan stasiun klimatologi',
                'product' => 'AWR',
                'product_headings' => ['Automatic Weather Recorder'],
                'profile_keywords' => ['AWR', 'Weather Forecast', 'klimatologi'],
            ],
            [
                'topic' => 'kualitas air sebagai indikator dini perubahan lingkungan',
                'angle' => 'bahas bagaimana pemantauan parameter kualitas air membantu respons lebih cepat terhadap perubahan sungai',
                'audience' => 'pengelola air baku, sungai, dan tim lingkungan',
                'product' => 'AWQR',
                'product_headings' => ['Automatic Water Quality Recorder'],
                'profile_keywords' => ['AWQR', 'kualitas air', 'Sungai Sepaku'],
            ],
            [
                'topic' => 'debit aliran sungai dan pentingnya data kontinu dalam pengelolaan DAS',
                'angle' => 'jelaskan hubungan level air, debit, dan kebutuhan validasi data lapangan',
                'audience' => 'pengelola DAS, irigasi, dan pos hidrologi',
                'product' => 'AFMR',
                'product_headings' => ['Automatic Flow Meter Recorder'],
                'profile_keywords' => ['AFMR', 'DAS', 'Water Security'],
            ],
            [
                'topic' => 'otomatisasi pintu air untuk operasi irigasi yang lebih responsif',
                'angle' => 'bahas manfaat kontrol pintu air online tanpa menjadikan artikel terlalu sales',
                'audience' => 'operator irigasi, pengelola bendung, dan dinas teknis',
                'product' => 'AWGC',
                'product_headings' => ['Automatic Water Gate Controller'],
                'profile_keywords' => ['AWGC', 'pintu air', 'irigasi'],
            ],
            [
                'topic' => 'monitoring deformasi struktur untuk membaca gejala risiko lebih awal',
                'angle' => 'jelaskan kenapa deformasi bendungan, lereng, dan struktur perlu dipantau secara berkala',
                'audience' => 'pengelola bendungan, geoteknik, dan konsultan struktur',
                'product' => 'ADR',
                'product_headings' => ['Automatic Deformation Recorder'],
                'profile_keywords' => ['ADR', 'deformasi', 'Structure & Deformation'],
            ],
            [
                'topic' => 'sensor vibrating wire dan monitoring geoteknik jangka panjang',
                'angle' => 'buat artikel yang menjembatani konsep sensor vibrating wire dengan kebutuhan data historis',
                'audience' => 'engineer geoteknik, bendungan, dan struktur besar',
                'product' => 'AVWR',
                'product_headings' => ['Automatic Vibrating Wire Recorder'],
                'profile_keywords' => ['AVWR', 'vibrating wire', 'geoteknik'],
            ],
            [
                'topic' => 'peringatan dini yang efektif dimulai dari data lapangan yang konsisten',
                'angle' => 'bahas EWS sebagai ekosistem sensor, threshold, komunikasi, dan respons masyarakat',
                'audience' => 'pengelola wilayah rawan banjir/longsor dan infrastruktur air',
                'product' => 'EWS',
                'product_headings' => ['Early Warning System'],
                'profile_keywords' => ['EWS', 'Early Warning', 'banjir'],
            ],
            [
                'topic' => 'pengukuran tekanan untuk infrastruktur kritis dan geothermal',
                'angle' => 'jelaskan peran data tekanan dalam well testing dan pemantauan aset berisiko',
                'audience' => 'engineer geothermal, pressure measurement, dan infrastruktur kritis',
                'product' => 'APLR',
                'product_headings' => ['Automatic Pressure Level Recorder'],
                'profile_keywords' => ['APLR', 'Pressure Measurement', 'geothermal'],
            ],
            [
                'topic' => 'dashboard telemetry sebagai pusat keputusan, bukan sekadar tampilan data',
                'angle' => 'bahas bagaimana integrasi sensor, logger, grafik, status perangkat, dan histori data membantu operasi',
                'audience' => 'manajer operasi, engineer, dan pengambil keputusan teknis',
                'product' => 'STESY',
                'product_headings' => ['Smart Telemetry System'],
                'profile_keywords' => ['STESY', 'Monitoring Terintegrasi', 'dashboard'],
            ],
        ],
    ],
];
