<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\SubSolution;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $ss = SubSolution::pluck('id', 'slug');

        $products = [
            // AWLR products
            ['sub_solution_id' => $ss['awlr'], 'name' => 'BE WLR-100-U150', 'slug' => 'be-wlr-100-u150', 'use_case' => 'Kanal Irigasi, Bendungan', 'highlight_points' => json_encode(['Jarak baca sensor 15 m','Dilengkapi Data Logger BL-110','Sensor tunggal','Data Online dan realtime 24 Jam']), 'description' => 'AWLR tipe ini menggunakan sensor ultrasonik dengan jarak baca hingga 15 meter. Dilengkapi dengan Data Logger Beacon 110 Series, AWLR seri ini sangat fleksibel karena cocok diaplikasikan untuk berbagai jenis aliran.', 'thumbnail' => 'konten/produk/gambar_thumbnail_produk/1744701020.webp', 'main_image' => 'konten/produk/gambar_produk/1744701021.webp', 'brochure_pdf' => 'konten/produk/brosur/1744710448_BROSUR BE WLR-100-U150.pdf', 'link_lkpp_general' => 'https://e-katalog.lkpp.go.id/katalog/produk/detail/43734714?type=general', 'link_lkpp_regency' => 'https://e-katalog.lkpp.go.id/katalog/produk/detail/3913629?type=regency', 'link_tkdn' => 'https://drive.google.com/file/d/1AYqlOr8xlpWkxpbB9ayiQ_hf6R4N12nJ/view', 'sort_order' => 1],
            ['sub_solution_id' => $ss['awlr'], 'name' => 'BE WLR-100-U014', 'slug' => 'be-wlr-100-u014', 'use_case' => 'Kanal Irigasi, Drainase, Kolam Retensi', 'highlight_points' => json_encode(['Jangkauan baca sensor 4 m','Dilengkapi Data Logger BL-110','Sensor tunggal','Data Online dan realtime 24 Jam']), 'description' => 'AWLR tipe ini menggunakan sensor ultrasonik dengan jarak baca hingga 4m. Solusi tepat pemantauan air di aliran kecil hingga menengah.', 'thumbnail' => 'konten/produk/gambar_thumbnail_produk/1744786219.webp', 'main_image' => 'konten/produk/gambar_produk/1744787191.webp', 'brochure_pdf' => 'konten/produk/brosur/1744710429_BROSUR BE WLR-100-U014.pdf', 'link_tkdn' => 'https://drive.google.com/file/d/1rYMG8QkJ4qr8opi0b_jT_xLcPRZB2O9m/view', 'sort_order' => 2],
            ['sub_solution_id' => $ss['awlr'], 'name' => 'BE WLR-100-R700', 'slug' => 'be-wlr-100-r700', 'highlight_points' => json_encode(['Jangkauan baca sensor 70 m','Dilengkapi Data Logger BL-110','Sensor tunggal','Data Online dan realtime 24 Jam']), 'description' => 'AWLR tipe ini menggunakan high end radar level sensor dengan jarak baca hingga 70 meter. Solusi tepat untuk aliran dengan volume besar.', 'thumbnail' => 'konten/produk/gambar_thumbnail_produk/1744700646.webp', 'main_image' => 'konten/produk/gambar_produk/1744700646.webp', 'brochure_pdf' => 'konten/produk/brosur/1744710217_BROSUR BE WLR-100-R700.pdf', 'link_tkdn' => 'https://drive.google.com/file/d/1odxUv1jBBvL6kzjLww2JT5gTKRqmRO5d/view', 'sort_order' => 3],
            ['sub_solution_id' => $ss['awlr'], 'name' => 'BE WLR-100-TD100', 'slug' => 'be-wlr-100-td100', 'highlight_points' => json_encode(['Jangkauan baca sensor 100 m','Dilengkapi Data Logger BL-110','Data Online dan realtime 24 Jam','Sensor tunggal']), 'description' => 'AWLR tipe ini menggunakan sensor tekanan dengan jarak baca hingga 100 meter. Solusi tepat untuk area tertutup dan sulit dijangkau.', 'thumbnail' => 'konten/produk/gambar_thumbnail_produk/1747726696.webp', 'main_image' => 'konten/produk/gambar_produk/1744700564.webp', 'brochure_pdf' => 'konten/produk/brosur/1744710091_BROSUR BE WLR-100-TD100.pdf', 'link_tkdn' => 'https://drive.google.com/file/d/1GQdpyoOIQM6aeF8VlgXQB7EtTXczkdDp/view', 'sort_order' => 4],
            // AWGC products
            ['sub_solution_id' => $ss['awgc'], 'name' => 'BE GCM-500-N1', 'slug' => 'be-gcm-500-n1', 'use_case' => 'Kanal Irigasi, Drainase', 'highlight_points' => json_encode(['Motorisasi manual','Multi gearbox + extended shaft','Dapat ditingkatkan ke motorisasi online']), 'description' => 'AWGC tipe manual ini dilengkapi actuator dan gearbox 1 x 2000 Nm, cocok untuk pintu air tersier dan wilayah irigasi lokal.', 'thumbnail' => 'konten/produk/gambar_thumbnail_produk/1745304296.webp', 'brochure_pdf' => 'konten/produk/brosur/1744710407_BROSUR BE GCM-500-N1.pdf', 'link_tkdn' => 'https://drive.google.com/file/d/1LrlU8XWP6ppPxesdDfxdsedWWoRsxV3E/view', 'sort_order' => 1],
            ['sub_solution_id' => $ss['awgc'], 'name' => 'BE WGC-1000-NE', 'slug' => 'be-wgc-1000-ne', 'use_case' => 'Kanal Irigasi, Bendungan, Drainase', 'highlight_points' => json_encode(['Kontrol Pintu Air 100% Online','Data realtime 24 jam non stop','Dilengkapi Data Logger BL-1100']), 'description' => 'AWGC seri terbaru dengan Data Logger BL-1100 yang memungkinkan kontrol pintu air sepenuhnya online.', 'thumbnail' => 'konten/produk/gambar_thumbnail_produk/1744700929.webp', 'main_image' => 'konten/produk/gambar_produk/1744700930.webp', 'brochure_pdf' => 'konten/produk/brosur/1744710381_BROSUR BE WGC-1000-NE.pdf', 'link_tkdn' => 'https://drive.google.com/file/d/1kkZ81p_0lQ90ql9xk0xj4qS_K8tp4liM/view', 'sort_order' => 2],
            ['sub_solution_id' => $ss['awgc'], 'name' => 'BE GCM-500-N2', 'slug' => 'be-gcm-500-n2', 'use_case' => 'Kanal Irigasi, Drainase', 'highlight_points' => json_encode(['Motorisasi manual','Multi gearbox + extended shaft','Dapat ditingkatkan ke motorisasi online']), 'description' => 'AWGC tipe manual dengan actuator dan gearbox hingga 2 x 2000 Nm untuk pintu air tersier.', 'thumbnail' => 'konten/produk/gambar_thumbnail_produk/1745304270.webp', 'main_image' => 'konten/produk/gambar_produk/1745304270.webp', 'sort_order' => 3],
            // AFMR
            ['sub_solution_id' => $ss['afmr'], 'name' => 'BE FMR-100-FS20', 'slug' => 'be-fmr-100-fs20', 'use_case' => 'Kanal Irigasi, Drainase', 'highlight_points' => json_encode(['Data Debit 24 Jam Non Stop','Jangkauan pengukuran hingga 0.03–20 m/s','Dilengkapi BL-1100']), 'description' => 'AFMR merupakan pilihan tepat untuk memantau debit air dan memberikan data realtime selama 24 jam.', 'thumbnail' => 'konten/produk/gambar_thumbnail_produk/1745313621.webp', 'main_image' => 'konten/produk/gambar_produk/1745313621.webp', 'sort_order' => 1],
            // ADR
            ['sub_solution_id' => $ss['adr'], 'name' => 'BE ADR-1000-RBT32', 'slug' => 'be-adr-1000-rbt32', 'use_case' => 'Bendungan', 'highlight_points' => json_encode(['Monitoring Deformasi 24 Jam','Kontrol penuh 100% Online','Jangkauan ukur hingga 3500 meter','Menggunakan prism target']), 'description' => 'ADR sangat tepat untuk memantau deformasi infrastruktur secara berkala tanpa risiko di lapangan.', 'thumbnail' => 'konten/produk/gambar_thumbnail_produk/1745399773.webp', 'main_image' => 'konten/produk/gambar_produk/1745399773.webp', 'sort_order' => 1],
            // AWQR
            ['sub_solution_id' => $ss['awqr'], 'name' => 'BE WQR-1000-MP7', 'slug' => 'be-wqr-1000-mp7', 'highlight_points' => json_encode(['8 parameter dalam satu perangkat','Kontrol penuh 100% Online','Jangkauan kedalaman hingga 61 meter']), 'description' => 'AWQR adalah pilihan tepat untuk memastikan kualitas air selalu termonitoring secara berkala.', 'thumbnail' => 'konten/produk/gambar_thumbnail_produk/1745983578.webp', 'main_image' => 'konten/produk/gambar_produk/1745983988.webp', 'brochure_pdf' => 'konten/produk/brosur/1745983371_BROSUR BE WQR-1000-MP7.pdf', 'sort_order' => 1],
            // AVWR
            ['sub_solution_id' => $ss['avwr'], 'name' => 'BE VWR-1000', 'slug' => 'be-vwr-1000', 'use_case' => 'Bendungan', 'highlight_points' => json_encode(['Data Logger BL-1100','Dapat berbagai macam sensor untuk mengukur Kawat Getar']), 'description' => 'Perangkat monitoring otomatis pengukuran getaran kawat dalam pemantauan jangka panjang.', 'thumbnail' => 'konten/produk/gambar_thumbnail_produk/1744700763.webp', 'main_image' => 'konten/produk/gambar_produk/1744700764.webp', 'brochure_pdf' => 'konten/produk/brosur/1744710317_BROSUR BE AVWR-1000.pdf', 'link_tkdn' => 'https://drive.google.com/file/d/1i-j8Fcz7R35KAULIFXjetwooZCtE83Oy/view', 'sort_order' => 1],
            // ARR
            ['sub_solution_id' => $ss['arr'], 'name' => 'BE RR-1000-TB02', 'slug' => 'be-rr-1000-tb02', 'use_case' => 'Bendungan', 'highlight_points' => json_encode(['Berbasis Magnetic Hall Effect','Resolusi hingga 0.2 mm','Akurasi ±2%','Material case Styrosun','Support multisensor']), 'description' => 'ARR pencatat curah hujan otomatis dengan basis sensor Magnetic Hall Effect, resolusi 0.2 mm dan akurasi ±2%.', 'thumbnail' => 'konten/produk/gambar_thumbnail_produk/1745909173.webp', 'main_image' => 'konten/produk/gambar_produk/1745909173.webp', 'link_tkdn' => 'https://drive.google.com/file/d/1FyN-lTSuGwDeG1NgHpl1SvRMuHI6lW5z/view', 'sort_order' => 1],
            ['sub_solution_id' => $ss['arr'], 'name' => 'BE RR-100-TB02', 'slug' => 'be-rr-100-tb02', 'use_case' => 'Bendungan', 'highlight_points' => json_encode(['Berbasis Magnetic Hall Effect','Resolusi hingga 0.2 mm','Akurasi ±2%','Material case Styrosun','Single sensor']), 'description' => 'ARR pencatat curah hujan otomatis dengan sensor Magnetic Hall Effect, single sensor.', 'thumbnail' => 'konten/produk/gambar_thumbnail_produk/1745909880.webp', 'main_image' => 'konten/produk/gambar_produk/1745909881.webp', 'brochure_pdf' => 'konten/produk/brosur/1745909881_BROSUR BE RR-100-TB02.pdf', 'link_tkdn' => 'https://drive.google.com/file/d/13TFOsKXPkgSaDGhb9IV1uYGX9V-fqdWI/view', 'sort_order' => 2],
            // AWR
            ['sub_solution_id' => $ss['awr'], 'name' => 'BE WR-1000-WS80', 'slug' => 'be-wr-1000-ws80', 'use_case' => 'Bendungan', 'highlight_points' => json_encode(['8 parameter dalam satu perangkat','Kontrol penuh 100% Online','Tepat dan Akurat']), 'description' => 'AWR tipe ini mampu mengukur 8 parameter cuaca sekaligus dengan satu sistem terintegrasi. IP65, kokoh untuk outdoor.', 'thumbnail' => 'konten/produk/gambar_thumbnail_produk/1744700846.webp', 'main_image' => 'konten/produk/gambar_produk/1744700846.webp', 'brochure_pdf' => 'konten/produk/brosur/1744710361_BROSUR BE AWR-1000-WS80.pdf', 'link_tkdn' => 'https://drive.google.com/file/d/1wdtl6vNQhpQrKeGXEe6Q64JaZ1fkBAxN/view', 'sort_order' => 1],
            // EWS
            ['sub_solution_id' => $ss['ews'], 'name' => 'BE EWS-100-WL', 'slug' => 'be-ews-100-wl', 'use_case' => 'Kanal Irigasi, Bendungan, Spillway, Drainase', 'highlight_points' => json_encode(['4 level peringatan + sound buzzer','Suara efektif 117 dB','Frekuensi lebar hingga 6500 Hz','Siaga 24 Jam Non Stop']), 'description' => 'Early Warning System berbasis multi-level visual dengan 4 level peringatan dan suara keras hingga 117 dB.', 'thumbnail' => 'konten/produk/gambar_thumbnail_produk/1744700792.webp', 'main_image' => 'konten/produk/gambar_produk/1744700792.webp', 'brochure_pdf' => 'konten/produk/brosur/1744710335_BROSUR BE EWS-100-WL.pdf', 'link_tkdn' => 'https://drive.google.com/file/d/1DnjusIOe05QkiFrppwt0bwcEnt7q20Mv/view', 'sort_order' => 1],
            // STESY
            ['sub_solution_id' => $ss['smart-telemetry-system'], 'name' => 'Smart Telemetry System', 'slug' => 'smart-telemetry-system', 'description' => 'STESY memungkinkan pemantauan data secara real-time dari perangkat telemetri yang tersebar di berbagai lokasi.', 'thumbnail' => 'konten/produk/gambar_thumbnail_produk/1744872999.webp', 'main_image' => 'konten/produk/gambar_produk/1744872999.webp', 'brochure_pdf' => 'konten/produk/brosur/1746157274_BROSUR STESY.pdf', 'sort_order' => 1],
            // APLR
            ['sub_solution_id' => $ss['aplr'], 'name' => 'BE PLR-1000', 'slug' => 'be-plr-1000', 'highlight_points' => json_encode(['Pengukuran level tekanan tanpa intervensi manual','Deteksi fluktuasi kecil dengan sensitivitas tinggi','Pengukuran tekanan hingga 3000 psi']), 'description' => 'APLR adalah alat pemantau otomatis untuk merekam dan mengirimkan data tekanan fluida secara real-time.', 'thumbnail' => 'konten/produk/gambar_thumbnail_produk/1745225630.webp', 'main_image' => 'konten/produk/gambar_produk/1745225630.webp', 'sort_order' => 1],
        ];

        foreach ($products as $data) {
            Product::create($data);
        }
    }
}
