<?php

namespace Database\Seeders;

use App\Models\Project;
use App\Models\Client;
use App\Models\ProjectCategory;
use Illuminate\Database\Seeder;

class ProjectSeeder2 extends Seeder
{
    public function run(): void
    {
        $cl = Client::pluck('id', 'name');
        $cat = ProjectCategory::pluck('id', 'slug');

        $projects = [
            ['client_id' => $cl['PT. Brantas Abipraya'], 'project_category_id' => $cat['irigasi'], 'name' => 'Telemetri AWQR Sungai Sepaku IKN', 'slug' => 'proyek-telemetri-awqr-sungai-sepaku-ikn', 'location' => 'Kalimantan Timur', 'year' => '2024', 'thumbnail' => 'projek_thumbnails/1744622458_5.webp', 'main_image' => 'projek_gambar_proyeks/WWCGTyTQp7CoBBt2xvJILhIRFoI0rjLSLFRWA7k5.webp', 'sort_order' => 15],
            ['client_id' => $cl['BBWS Serayu Opak'], 'project_category_id' => $cat['irigasi'], 'name' => 'Telemetri AFMR & ARR DAS Bogowonto', 'slug' => 'proyek-telemetri-afmr-arr-das-bogowonto', 'location' => 'Jawa Barat', 'year' => '2024', 'thumbnail' => 'projek_thumbnails/1744622304_4.webp', 'main_image' => 'projek_gambar_proyeks/R2w2dkyAqBD1sRjfTpTlbVHpdVy6hOpSOZKnINi1.webp', 'sort_order' => 16],
            ['client_id' => $cl['PT. Brantas Abipraya'], 'project_category_id' => $cat['irigasi'], 'name' => 'Telemetri AWLR Bendungan Sepaku IKN', 'slug' => 'proyek-telemetri-awlr-bendungan-sepaku-ikn', 'location' => 'Kalimantan Timur', 'year' => '2024', 'thumbnail' => 'projek_thumbnails/HUAoAo72YInyGLidCgO2beSIK5JYL5lYBmsCHHFI.webp', 'main_image' => 'projek_gambar_proyeks/vUP9kVWgPQ1URLMwJ18KyVs26PqiKcTUMsgoBJEz.webp', 'is_featured' => true, 'sort_order' => 17],
            ['client_id' => $cl['Dinas PUSDA Provinsi Jawa Timur'], 'project_category_id' => $cat['irigasi'], 'name' => 'Telemetri AWQR Sidoarjo', 'slug' => 'proyek-telemetri-awqr-sidoarjo', 'location' => 'Jawa Timur', 'year' => '2023', 'thumbnail' => 'projek_thumbnails/4oq5Hw4qyGjG3i3CiYj6UyZAA8d16aDYzWSu4TdH.webp', 'main_image' => 'projek_gambar_proyeks/QvM4QQL9g0mzhxrmyvp3GihLY0Tykwv0yOUUhlCi.webp', 'sort_order' => 18],
            ['client_id' => $cl['BBWS Cimanuk Cisanggarung'], 'project_category_id' => $cat['irigasi'], 'name' => 'Telemetri AWGC Bendung Cikeusik', 'slug' => 'proyek-telemetri-awgc-bendung-cikeusik', 'location' => 'Jawa Barat', 'year' => '2023', 'thumbnail' => 'projek_thumbnails/DSe7wbJ08IqV1CJtr9zwvcIuDGr5wyd1ovtY0F8Z.webp', 'main_image' => 'projek_gambar_proyeks/dMGGkHtnhBCrsgz6g9akKrGbAPyLcMjxy9rmJROr.webp', 'sort_order' => 19],
            ['client_id' => $cl['BBWS Ciliwung Cisadane'], 'project_category_id' => $cat['irigasi'], 'name' => 'Telemetri AWGC Sungai Cisadane', 'slug' => 'proyek-telemetri-awgc-sungai-cisadane', 'location' => 'Jawa Barat', 'year' => '2023', 'thumbnail' => 'projek_thumbnails/1744622009_3.webp', 'main_image' => 'projek_gambar_proyeks/IIIJ52DyLQPdkK6EFHH4hjrHYu3JiuQq3IPYGWox.webp', 'sort_order' => 20],
            ['client_id' => $cl['Dinas SDA Provinsi DKI Jakarta'], 'project_category_id' => $cat['irigasi'], 'name' => 'Telemetri AWLR DSDA DKI Jakarta', 'slug' => 'proyek-telemetri-awlr-dsda-dki-jakarta', 'location' => 'Jakarta', 'year' => '2022', 'thumbnail' => 'projek_thumbnails/vUdHGJu6IXjY8gH6LqL4xT1W5HrMxuI29YLCQvCy.webp', 'main_image' => 'projek_gambar_proyeks/rqa2aoyuVaIM2WAELSF5wCUOQlIHKFljWY145w5f.webp', 'sort_order' => 21],
            ['client_id' => $cl['Dinas PUSDA Provinsi Jawa Timur'], 'project_category_id' => $cat['irigasi'], 'name' => 'Telemetri AWLR PUSDA Jawa Timur Hidrologi', 'slug' => 'proyek-telemetri-awlr-pusda-jawa-timur-hidrologi', 'location' => 'Jawa Timur', 'year' => '2022', 'thumbnail' => 'projek_thumbnails/Ytgm9tOqxCWt5j2JcmjlrpFdcT8S3wohyWmN2RN8.webp', 'main_image' => 'projek_gambar_proyeks/fCZZAuvwpTWBBAFLCVTd6OJ7eesJuzasRUGg75pO.webp', 'sort_order' => 22],
            ['client_id' => $cl['BBWS Serayu Opak'], 'project_category_id' => $cat['irigasi'], 'name' => 'Telemetri AWLR BBWS Serayu Opak Hidrologi', 'slug' => 'proyek-telemetri-awlr-bbws-serayu-opak-hidrologi', 'location' => 'Yogyakarta', 'year' => '2016', 'thumbnail' => 'projek_thumbnails/PtwEWZZbDTNWx4iWLc7cDN8sgTJATqhMeZybx4B8.webp', 'main_image' => 'projek_gambar_proyeks/s9JI86UVRjxEWUDDlBLOyhgg7GYZ2Nh2UYIxfk6K.webp', 'sort_order' => 23],
            // Bendungan
            ['client_id' => $cl['BWS Sumatra I Aceh'], 'project_category_id' => $cat['bendungan'], 'name' => 'Telemetri Bendungan Keureuto 2024', 'slug' => 'proyek-telemetri-bendungan-keureuto', 'location' => 'Aceh Utara', 'year' => '2024', 'thumbnail' => 'projek_thumbnails/1748573716_Gambar Proyek Bawah.webp', 'main_image' => 'projek_gambar_proyeks/dy1RycPfJ1g06YurPksta3zonbznmdnr9vd8i5rx.webp', 'white_paper_url' => 'https://drive.google.com/file/d/1ha3Jq5pNU5mAkJNLcJNzadS5iM_rxIAd/view', 'is_featured' => true, 'sort_order' => 24],
            ['client_id' => $cl['BBWS Ciliwung Cisadane'], 'project_category_id' => $cat['bendungan'], 'name' => 'Telemetri ADR Bendungan Ciawi', 'slug' => 'proyek-telemetri-adr-bendungan-ciawi', 'location' => 'Jawa Barat', 'year' => '2024', 'thumbnail' => 'projek_thumbnails/bcSq5GsBMuytCKFj4XoMNtBW3byK9585xQ8fkuSS.webp', 'main_image' => 'projek_gambar_proyeks/anDfw1Dx5hfgN8J5Th8SSkieYRvaBb75hHrZEpnO.webp', 'sort_order' => 25],
            ['client_id' => $cl['BBWS Citarum'], 'project_category_id' => $cat['bendungan'], 'name' => 'Telemetri AWLR & AVWR Bendungan Situ Lembang', 'slug' => 'proyek-telemetri-awlr-avwr-bendungan-situ-lembang', 'location' => 'Jawa Barat', 'year' => '2023', 'thumbnail' => 'projek_thumbnails/hvw0hzNXKMeSrJQvj4zC3AZDIOmOSRUCU0aAgoxU.webp', 'main_image' => 'projek_gambar_proyeks/uU9ZYLEic9FKZbVrLwsabaZ0vBkHN6ijKdNIkA6b.webp', 'sort_order' => 26],
            ['client_id' => $cl['BBWS Brantas'], 'project_category_id' => $cat['bendungan'], 'name' => 'Telemetri ARR & AWR Bendungan Bagong', 'slug' => 'proyek-telemetri-arr-awr-bendungan-bagong', 'location' => 'Jawa Timur', 'year' => '2023', 'thumbnail' => 'projek_thumbnails/Tk2ppx1stJO3DBJUhvmjeMkunMEXBJRkB1L4RU7d.webp', 'main_image' => 'projek_gambar_proyeks/utLGVGMOsh3xaiVAk5BgRpaRGdulbvC8DbcRFefA.webp', 'sort_order' => 27],
            ['client_id' => $cl['BBWS Cimanuk Cisanggarung'], 'project_category_id' => $cat['bendungan'], 'name' => 'Telemetri AWLR Bendungan Cipanas', 'slug' => 'proyek-telemetri-awlr-bendungan-cipanas', 'location' => 'Jawa Barat', 'year' => '2023', 'thumbnail' => 'projek_thumbnails/1744622632_6.webp', 'main_image' => 'projek_gambar_proyeks/vDDdndmUVDSO259Xa4HKSGmnE3lmAsozfItYU404.webp', 'sort_order' => 28],
            ['client_id' => $cl['BBWS Serayu Opak'], 'project_category_id' => $cat['bendungan'], 'name' => 'Telemetri AWLR & EWS Bendungan Bener', 'slug' => 'proyek-telemetri-awlr-ews-bendungan-bener', 'location' => 'Jawa Tengah', 'year' => '2022', 'thumbnail' => 'projek_thumbnails/GgsjRkytvRy95hDLNLJ7Qg3XwTd9m3SrFHwj1RnV.webp', 'main_image' => 'projek_gambar_proyeks/uVmIqR3MuAve65zKDeW4Ef7MdRa1YcDbularKw3C.webp', 'sort_order' => 29],
            ['client_id' => $cl['BBWS Brantas'], 'project_category_id' => $cat['bendungan'], 'name' => 'Telemetri AWLR Bendungan Semantok', 'slug' => 'proyek-telemetri-awlr-bendungan-semantok', 'location' => 'Jawa Timur', 'year' => '2022', 'thumbnail' => 'projek_thumbnails/FHIgYWBXvSR8jsK4KkwRv2bPsIQGtzIG3DqSgCch.webp', 'main_image' => 'projek_gambar_proyeks/7x32rVVzIiE7HpewLezvKQsuXxfZJ7aPfwpYMwi5.webp', 'sort_order' => 30],
            ['client_id' => $cl['BWS NT1'], 'project_category_id' => $cat['bendungan'], 'name' => 'Telemetri AWR Bendungan Bintang Bano', 'slug' => 'proyek-telemetri-awr-bendungan-bintang-bano', 'location' => 'Nusa Tenggara Barat', 'year' => '2022', 'thumbnail' => 'projek_thumbnails/qo4fddOJEJAHthARVqKXOAcAbDwxSyYnL6M3Qn5A.webp', 'main_image' => 'projek_gambar_proyeks/xBRBvY2P8E5Y0Ox9gtvFYuiY8fTEE5UrFAuuioMw.webp', 'sort_order' => 31],
            ['client_id' => $cl['BWS NT2'], 'project_category_id' => $cat['bendungan'], 'name' => 'Telemetri AWR Bendungan Napungete', 'slug' => 'proyek-telemetri-awr-bendungan-napungete', 'location' => 'Nusa Tenggara Timur', 'year' => '2021', 'thumbnail' => 'projek_thumbnails/fuOG8j0Hs4wJ6KYaH7Ns9QKTnVYug8naqPwqB76J.webp', 'main_image' => 'projek_gambar_proyeks/q6wuX3SXnc1ilqa210VFFgO2Lz918mB1f3JksxEs.webp', 'sort_order' => 32],
            ['client_id' => $cl['BBWS Bengawan Solo'], 'project_category_id' => $cat['bendungan'], 'name' => 'Telemetri AWR, AWLR, & AVWR Bendungan Tukul', 'slug' => 'proyek-telemetri-awr-awlr-avwr-bendungan-tukul', 'location' => 'Jawa Timur', 'year' => '2021', 'thumbnail' => 'projek_thumbnails/tQsADFN1a0TSyKpdwpuDcsWT3tTaJNEAsk6Kvn5x.webp', 'main_image' => 'projek_gambar_proyeks/lPetuqwPM58Mz6u9VN1tuoqhBczgKHYepDQyLj3M.webp', 'sort_order' => 33],
            ['client_id' => $cl['BBWS Cimanuk Cisanggarung'], 'project_category_id' => $cat['bendungan'], 'name' => 'Telemetri AWR Bendungan Kuningan', 'slug' => 'proyek-telemetri-awr-bendungan-kuningan', 'location' => 'Jawa Barat', 'year' => '2021', 'thumbnail' => 'projek_thumbnails/u4xW2L1BTPsrYDc4oYK7myIow3S54upcqIM6oVr7.webp', 'main_image' => 'projek_gambar_proyeks/shvQHcmW2dMpN7aElzoGpSZ2n4NdXy2HhsljgfK8.webp', 'sort_order' => 34],
            ['client_id' => $cl['PT. Adhi Karya'], 'project_category_id' => $cat['bendungan'], 'name' => 'Telemetri AWR Bendungan Jlantah', 'slug' => 'proyek-telemetri-awr-bendungan-jlantah', 'location' => 'Jawa Tengah', 'year' => '2021', 'thumbnail' => 'projek_thumbnails/HnPzliq3vEszSnONzT9vRciL3JD3yAFqikM1ZwtB.webp', 'main_image' => 'projek_gambar_proyeks/DxWazxAal3SchWeRh8YJLG72B9fw9jXLZP9dLdxA.webp', 'sort_order' => 35],
            ['client_id' => $cl['BBWS Citanduy'], 'project_category_id' => $cat['bendungan'], 'name' => 'Telemetri EWS Bendungan Leuwikeris', 'slug' => 'proyek-telemetri-ews-bendungan-leuwikeris', 'location' => 'Jawa Barat', 'year' => '2021', 'thumbnail' => 'projek_thumbnails/kwpd0kHUN9sMlmtT19hSwred78K80hYMXzs2bJfL.webp', 'main_image' => 'projek_gambar_proyeks/AyynyIgzzIwxz62iAziSVguIQgjE7soUpEkiRV92.webp', 'sort_order' => 36],
            ['client_id' => $cl['BBWS Serayu Opak'], 'project_category_id' => $cat['bendungan'], 'name' => 'Telemetri AWLR & AVWR Bendungan Sermo', 'slug' => 'proyek-telemetri-awlr-avwr-bendungan-sermo', 'location' => 'Yogyakarta', 'year' => '2014', 'thumbnail' => 'projek_thumbnails/QKHGKOnzxgo9XpJY41VVVZ2rjUbe1rg2ZqDU3hzh.webp', 'main_image' => 'projek_gambar_proyeks/PCzyFITs7ueXnGueTh2JWFrdczOwxmb8ICl3B9Wi.webp', 'sort_order' => 37],
            // Klimatologi
            ['client_id' => $cl['Perum. Jasa Tirta I'], 'project_category_id' => $cat['klimatologi'], 'name' => 'Telemetri ARR Perum Jasa Tirta I Surabaya', 'slug' => 'proyek-telemetri-arr-perum-jasa-tirta-i-surabaya', 'location' => 'Jawa Timur', 'year' => '2023', 'thumbnail' => 'projek_thumbnails/TzY3QqWwsite6bHW16MExKkdwxw3P6IeqQkslwjn.webp', 'main_image' => 'projek_gambar_proyeks/o1UZ9NMUmYx8VaU6WylFKJtDdedNwpFRh2qQGcgn.webp', 'sort_order' => 38],
            ['client_id' => $cl['Dinas PUSDA Provinsi Jawa Timur'], 'project_category_id' => $cat['klimatologi'], 'name' => 'Telemetri ARR PUSDA Jawa Timur', 'slug' => 'proyek-telemetri-arr-pusda-jawa-timur', 'location' => 'Jawa Timur', 'year' => '2023', 'thumbnail' => 'projek_thumbnails/iW56hFymf7B753PMWvBtgerA4mR9YXo8x8OtFCWB.webp', 'main_image' => 'projek_gambar_proyeks/5rctL5OIjeQxlhAFzlZbkAmXhrowA2o7dI9kgbfB.webp', 'sort_order' => 39],
            ['client_id' => $cl['SDA ESDM Provinsi DIY'], 'project_category_id' => $cat['klimatologi'], 'name' => 'Telemetri ARR & AWR PSDA Yogyakarta', 'slug' => 'proyek-telemetri-arr-awr-psda-yogyakarta', 'location' => 'Yogyakarta', 'year' => '2016', 'thumbnail' => 'projek_thumbnails/DuWGWy0ZiEJXFGuPooXwhNWbKpX4V7j4hNnPoNAE.webp', 'main_image' => 'projek_gambar_proyeks/cFQr2fBnTHH4hZ2z55w7KY74vX1CkWMIQKLUE096.webp', 'sort_order' => 40],
            ['client_id' => $cl['SDA ESDM Provinsi DIY'], 'project_category_id' => $cat['klimatologi'], 'name' => 'Telemetri ARR & AWR Kaliurang', 'slug' => 'proyek-telemetri-arr-awr-kaliurang', 'location' => 'Yogyakarta', 'year' => '2014', 'thumbnail' => 'projek_thumbnails/M8PHY1Kehv5J6mK8BV3bC2URURvBeNFDZ7XZUKZQ.webp', 'main_image' => 'projek_gambar_proyeks/56ySG4CurjAL3CBMBFb5hifzZi8NJP3ONuIqquT5.webp', 'sort_order' => 41],
            // Geothermal
            ['client_id' => $cl['PT. Medco Energi'], 'project_category_id' => $cat['geothermal'], 'name' => 'Telemetri APLR Kawah Ijen', 'slug' => 'proyek-telemetri-aplr-kawah-ijen', 'location' => 'Jawa Timur', 'year' => '2023', 'thumbnail' => 'projek_thumbnails/P65dR90QEUtfKZKBmnI3StyEuTyGDQ5M0BPYWU1O.webp', 'main_image' => 'projek_gambar_proyeks/PO55U8KkDkgnUMXf6bZnXQ0gi5zchTLDSpugByHe.webp', 'sort_order' => 42],
            // Bendo
            ['client_id' => $cl['BBWS Bengawan Solo'], 'project_category_id' => $cat['bendungan'], 'name' => 'Telemetri AWR Bendungan Bendo', 'slug' => 'proyek-telemetri-awr-bendungan-bendo', 'location' => 'Jawa Timur', 'year' => '2021', 'thumbnail' => 'projek_thumbnails/vRf49TZg5euqBxTYBuqNklpfu6LwsikDI0XvZDP0.webp', 'main_image' => 'projek_gambar_proyeks/1FWnS22QG1guRbJd61m1Q8i9KJfiZpabW6a1Y1s6.webp', 'sort_order' => 43],
        ];

        foreach ($projects as $data) {
            Project::create($data);
        }
    }
}
