<?php

namespace Database\Seeders;

use App\Models\SubSolution;
use App\Models\Solution;
use Illuminate\Database\Seeder;

class SubSolutionSeeder extends Seeder
{
    public function run(): void
    {
        $ws = Solution::where('slug', 'water-security')->first()->id;
        $wf = Solution::where('slug', 'weather-forecast')->first()->id;
        $ew = Solution::where('slug', 'early-warning')->first()->id;
        $pm = Solution::where('slug', 'pressure-measurement')->first()->id;
        $st = Solution::where('slug', 'stesy')->first()->id;

        $subs = [
            ['solution_id' => $ws, 'name' => 'Automatic Water Level Recorder', 'slug' => 'awlr', 'abbreviation' => 'AWLR', 'main_content' => 'Automatic Water Level Recorder atau AWLR adalah perangkat telemetri yang dirancang untuk mengukur ketinggian muka air secara otomatis dan 100% online. Teknologi AWLR ini memudahkan pemantauan volume dan debit air tanpa perlu inspeksi manual, menjadikannya solusi ideal untuk sistem irigasi, bendungan, dan pengelolaan sumber daya air lainnya.', 'support_content' => 'Wilayah aliran butuh banyak sensor? Tentu saja bisa! AWLR dapat dikombinasikan dengan berbagai sensor tambahan untuk menunjang pengambilan data yang komperhensif.', 'application_content' => 'AWLR dapat terpasang dan membaca data secara online dari berbagai karakteristik aliran: Aliran Irigasi, Bendungan (area spillway dan V-Notch), Kanal Drainase.', 'icon' => 'subsolution_images/icon/1742442506_icon awlr.webp', 'video_url' => 'https://www.youtube.com/watch?v=L0EI3GI7RrU', 'file_3d_local' => 'uploads/subsolution_files/AWLR_NEW.html', 'link_3d' => 'https://stesy.beacontelemetry.com/image/AWLR_NEW.html', 'sort_order' => 1],
            ['solution_id' => $ws, 'name' => 'Automatic Water Gate Controller', 'slug' => 'awgc', 'abbreviation' => 'AWGC', 'main_content' => 'Automatic Water Gate Controller atau AWGC adalah solusi telemetri yang dirancang khusus untuk mengontrol buka-tutup pintu air secara otomatis dan online, tanpa perlu intervensi manual di lapangan.', 'support_content' => 'Wilayah pemasangan perlu sensor tambahan? Tentu saja bisa! AWGC dapat dikombinasikan dengan berbagai sensor tambahan untuk menunjang pengambilan data yang komperhensif.', 'application_content' => 'AWGC cocok dipasang di: Pintu Air Irigasi, Pintu Air Bendung, Valve Bendungan, Pintu Spillway.', 'icon' => 'subsolution_images/icon/1742442487_icon awgc.webp', 'video_url' => 'https://www.youtube.com/watch?v=zDCz8D8ig5E', 'file_3d_local' => 'uploads/subsolution_files/AWGC.html', 'link_3d' => 'https://stesy.beacontelemetry.com/image/AWGC.html', 'sort_order' => 2],
            ['solution_id' => $ws, 'name' => 'Automatic Flow Meter Recorder', 'slug' => 'afmr', 'abbreviation' => 'AFMR', 'main_content' => 'Automatic Flowmeter Recorder (AFMR) merupakan perangkat telemetri khusus untuk mengukur debit aliran air secara terus-menerus tanpa perlu inspeksi langsung ke lapangan.', 'support_content' => 'AFMR Beacon Engineering dapat dikombinasikan dengan sensor lain untuk kebutuhan pengukuran multi-parameter.', 'application_content' => 'AFMR cocok dipasang di: Saluran Irigasi, Kanal atau Sungai Pemantau Banjir, Intake Pembangkit Listrik Tenaga Air, Jembatan Sungai.', 'icon' => 'subsolution_images/icon/1742442473_icon afmr.webp', 'video_url' => 'https://www.youtube.com/watch?v=C9B0mlGpMMA', 'file_3d_local' => 'uploads/subsolution_files/AFMR.html', 'link_3d' => 'https://stesy.beacontelemetry.com/image/AFMR.html', 'sort_order' => 3],
            ['solution_id' => $ws, 'name' => 'Automatic Deformation Recorder', 'slug' => 'adr', 'abbreviation' => 'ADR', 'main_content' => 'ADR Beacon Engineering adalah sistem telemetri otomatis yang dirancang untuk memantau deformasi atau pergeseran struktur secara real-time, akurat, dan tanpa intervensi manual ke lapangan.', 'support_content' => null, 'application_content' => 'ADR cocok dipasang di: Konstruksi Bendungan, Lereng dan tebing rawan longsor, Terowongan.', 'icon' => 'subsolution_images/icon/1742442450_icon adr.webp', 'video_url' => 'https://www.youtube.com/watch?v=zDCz8D8ig5E', 'file_3d_local' => null, 'link_3d' => null, 'sort_order' => 4],
            ['solution_id' => $ws, 'name' => 'Automatic Water Quality Recorder', 'slug' => 'awqr', 'abbreviation' => 'AWQR', 'main_content' => 'Automatic Water Quality Recorder atau AWQR adalah sistem pemantauan kualitas air otomatis yang terintegrasi dengan Data Logger Beacon Engineering BL-1100.', 'support_content' => null, 'application_content' => 'AWQR cocok dipasang di: Sungai dan Kanal Irigasi, Spillway dan Waduk, Hulu-hilir sungai, Instalasi Pengolahan Air, Area Industri dan Pembuangan Limbah.', 'icon' => 'subsolution_images/icon/1742442429_icon awqr.webp', 'video_url' => 'https://www.youtube.com/watch?v=zDCz8D8ig5E', 'file_3d_local' => null, 'link_3d' => 'https://stesy.beacontelemetry.com/image/AWQR.html', 'sort_order' => 5],
            ['solution_id' => $ws, 'name' => 'Automatic Vibrating Wire Recorder', 'slug' => 'avwr', 'abbreviation' => 'AVWR', 'main_content' => 'Automatic Vibrating Wire Recorder (AVWR) adalah solusi telemetri otomatis untuk pemantauan sensor getaran kawat (vibrating wire) dalam jangka panjang.', 'support_content' => null, 'application_content' => 'AVWR cocok dipasang di: Bendungan, Lereng Sekitar Bendungan, Terowongan, Jembatan.', 'icon' => 'subsolution_images/icon/1742442410_icon avwr.webp', 'video_url' => 'https://www.youtube.com/watch?v=zDCz8D8ig5E', 'file_3d_local' => null, 'link_3d' => null, 'sort_order' => 6],
            ['solution_id' => $wf, 'name' => 'Automatic Rain Recorder', 'slug' => 'arr', 'abbreviation' => 'ARR', 'main_content' => 'Automatic Rain Recorder atau ARR adalah perangkat telemetri pengukur curah hujan digital yang menggunakan mekanisme tipping bucket untuk pencatatan data hujan secara otomatis.', 'support_content' => 'ARR juga memungkinkan penggabungan data hujan dengan parameter lain seperti tinggi muka air.', 'application_content' => 'ARR cocok dipasang di: Catchment Area Bendungan dan Irigasi, Dataran Tinggi, Hulu Sungai.', 'icon' => 'subsolution_images/icon/1742442395_icon arr.webp', 'video_url' => 'https://youtu.be/XQf-5R0oNqg?si=vQm3OdZpN4_z9V8C', 'file_3d_local' => null, 'link_3d' => null, 'sort_order' => 1],
            ['solution_id' => $wf, 'name' => 'Automatic Weather Recorder', 'slug' => 'awr', 'abbreviation' => 'AWR', 'main_content' => 'Automatic Weather Recorder atau AWR adalah perangkat telemetri untuk pemantauan cuaca otomatis dan berkelanjutan.', 'support_content' => null, 'application_content' => 'AWR cocok dipasang di: Wilayah Sekitar Bendungan, Area Irigasi, Stasiun Klimatologi dan Meteorologi.', 'icon' => 'subsolution_images/icon/1742442255_icon awr.webp', 'video_url' => 'https://www.youtube.com/watch?v=zDCz8D8ig5E', 'file_3d_local' => null, 'link_3d' => null, 'sort_order' => 2],
            ['solution_id' => $ew, 'name' => 'Early Warning System', 'slug' => 'ews', 'abbreviation' => 'EWS', 'main_content' => 'Early Warning System atau EWS merupakan perangkat telemetri peringatan dini otomatis yang dirancang untuk memberikan notifikasi cepat dan efektif terhadap potensi bencana.', 'support_content' => 'Wilayah monitoring butuh banyak sensor? Tentu saja bisa! EWS dapat dikombinasikan dengan lebih dari satu sensor.', 'application_content' => 'EWS cocok dipasang di: Bendungan, Hilir Sungai, Daerah Bantaran Sungai, Permukiman Warga.', 'icon' => 'subsolution_images/icon/1742442230_icon ews.webp', 'video_url' => 'https://www.youtube.com/watch?v=zDCz8D8ig5E', 'file_3d_local' => null, 'link_3d' => null, 'sort_order' => 1],
            ['solution_id' => $pm, 'name' => 'Automatic Pressure Level Recorder', 'slug' => 'aplr', 'abbreviation' => 'APLR', 'main_content' => 'APLR adalah alat pemantauan tekanan otomatis yang digunakan untuk merekam dan mengirimkan data tekanan fluida secara real-time.', 'support_content' => 'Kawasan memerlukan sensor tambahan? Tentu saja bisa! APLR dapat dikombinasikan dengan berbagai sensor tambahan.', 'application_content' => 'APLR cocok dipasang di: Area gas dan panas bumi (geothermal), Bendungan dan waduk, Pipa bawah tanah dan sistem hidrolik.', 'icon' => 'subsolution_images/icon/1747723209_Pressure_Monitoring_Device_Icon-removebg-preview.webp', 'video_url' => 'https://www.youtube.com/watch?v=zDCz8D8ig5E', 'file_3d_local' => null, 'link_3d' => null, 'sort_order' => 1],
            ['solution_id' => $st, 'name' => 'Smart Telemetry System', 'slug' => 'smart-telemetry-system', 'abbreviation' => 'STESY', 'main_content' => 'STESY hadir sebagai platform monitoring real-time yang menjamin integrasi penuh. Data teknis dikirim langsung dari lapangan secara otomatis, selama 24 jam non stop.', 'support_content' => null, 'application_content' => 'STESY mendukung: Integrasi via Open API, Autentikasi login modern, Kontrol akses berbasis peran (RBAC), Audit log, Antarmuka Interaktif & Responsif, Ekspor Data.', 'icon' => 'subsolution_images/icon/1747723411_ChatGPT_Image_May_20__2025__01_42_30_PM-removebg-preview.png', 'video_url' => 'https://www.youtube.com/watch?v=qD1ePHATQ4o', 'file_3d_local' => null, 'link_3d' => null, 'sort_order' => 1],
        ];

        foreach ($subs as $data) {
            SubSolution::create($data);
        }
    }
}
